version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: { username here }
      MONGO_INITDB_ROOT_PASSWORD: { pw here }
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: { username }
      ME_CONFIG_MONGODB_ADMINPASSWORD: { pw }
      ME_CONFIG_MONGODB_URL: mongodb://{username}:{pw}@mongo:27017/
